### ISSUE TITLE
Data files no longer available

### ISSUE THREAD

**Issue by Ming446** [iris-edu/EMC-ParaView#2]
I have edited the source code to work for python3. Now I hope to plot volcano locations and slabs from SLAB1.0/SLAB2.0. However, these files got deleted on the website. https://ds.iris.edu/ds/products/emc-desktoptools/

Where could I find them? 

Minghao Zhang, University of Cambridge

**Comment by manoch-iris** [comment]
Minghao, Why are you looking for that URL? If you do not have a local copy, Plugins should automatically download the files. I just tried them on my machine and worked. Just follow instructions in the tutorial. Select the volcano and slab options from the menu. Please let me know if you are having problems.

Best,
--manoch
<img width="666" alt="Screen Shot 2021-08-03 at 7 09 15 AM" src="https://user-images.githubusercontent.com/5756394/128030397-215bcf56-ae68-46fd-bdaa-4754a8302206.png">

**Comment by Ming446** [comment]
Hi Manoch, 
Thank you so much for your reply. I'm searching for the url because of this error:

Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "<string>", line 20, in RequestInformation
Exception: volcano file "/Users/minghaozhang/Documents/EMC-ParaView-R.1.5.6/data/volcanoes/WOVOdat_volcano_locations.csv" not found! Please provide the full path or UR for the file. Aborting.
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "<string>", line 18, in RequestData
ModuleNotFoundError: No module named 'urlparse'

**Comment by manoch-iris** [comment]
Hi Minghao,

The way Plugins work is to check your data directory under the installation first to see if the file they are looking for exists. In your case it does not, then it tries to download the file from the Web based on your configuration file. Based on the last line in your log: "ModuleNotFoundError: No module named 'urlparse'" the issue is with urlparse. I think this module exist in Python 2.7 but was renamed to urllib.parse in Python 3. Check and make sure that is the case. So, as part of your upgrade to Python 3, you need to make necessary changes for this module. We will have our Python 3 version out but we still do not have a date yet. I hope this helps
